[package]
name = "lart-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
vsvg = { git = "https://github.com/abey79/vsvg" }
vsvg-viewer = { git = "https://github.com/abey79/vsvg" }
